version: '3.4'

#-----------------------------------------------------------------------------------
networks:
    app_net:
#-----------------------------------------------------------------------------------
services:
    helpdesk:
        image: ${DOCKER_REGISTRY-}helpdesk
        build:
            context: .
            dockerfile: HelpDesk/Dockerfile
        restart: always
        networks: 
        - app_net
#-----------------------------------------------------------------------------------
    #prometheus:
    #    image: quay.io/prometheus/prometheus:latest
    #    depends_on:
    #            - helpdesk
    #    ports:
    #            - 9090:9090
    #    volumes:
    #            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    #    restart: always
    #    networks: 
    #            - app_net
#-----------------------------------------------------------------------------------
    #grafana: 
    #    image: grafana/grafana
    #    depends_on: 
    #        - prometheus
    #    #command:
    #    environment:
    #            - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
    #            - GF_USERS_ALLOW_SIGN_UP=false
    #    restart: always
    #    ports:
    #            - 3000:3000
    #    networks:
    #            - app_net

#-----------------------------------------------------------------------------------
